language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - libgconf-2-4
    - libcurl3
cache:
  yarn: true
install:
- yarn install --ignore-engines
before_script:
- yarn start --silent &
script:
- npm run lint
- npm run test:unit
- npm run test:func
deploy:
  provider: heroku
  api_key:
    secure: ZpyVZEpmlc85HlnlPi9FXeljHkgj5CyNazfb9MWSCY4/noo8T9HcnAjO2Or9Wk0oNpG08HUfZYz0XIdojLHxuqJWGdEODzl/ciKg+lsqV0fX0+ltNczIpilLh8/cvD5TRHE+3RPWrOPtuaEuF89yWMNSXYVm4+NDVKW1poEDwP0GooayXFn/SlWs5j1ZSEMKllo/T95zO+e134jjc0aoTj6ZLLG6vRLjOohZo/O5sAxv0q02S+HsJSLYjIUxR+w6OULj0Qf7JnCnmNJ2p79iO0qHPSSUb2X8CqHC/s8a1i4dKFb9VU8QG1ozMgx2Ujuko/3KiNDN4mJoFdn/Vhh6cSTBNdEawkz55qKlQeFxzm4rsTCTja5IWJHzoNxXVKdLhUnEIRZIGAEWmw/8Pls8sp9/ev1lgm2q8xs1NfP5laHVb9J/dFrcgL/pPp6axaMUfLfxxubHxirjtPWG7WrRxRkuUMTZfDCyJfjjcCKvHQrVjEU2mqgnPtm6DGMWEIWxjXMjJrB2TaXdmPh6mWVNGsdM2PkNi4tQ1lMcbESDJSCRlXF1REkfcMMwDQyf2vRR55b1ntWdlDYifD0ugHkQkBApaOZL/yv3Q9VCjRRLbKjuVgD+07XJ3BSyFRUe1U5pqpmX1lCY6gd7QrPHaYjyYIp7gRRC0Ekr1+QIYpwBems=
  app: pipedrive-bling-integration
  on:
    repo: olucasgomes/pipedrive-bling-integration
