language: node_js
node_js:
- node
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  yarn: true
install:
- yarn install --ignore-engines
before_script:
- yarn start --silent &
script:
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: T243FBSe2CxS6h+WK7ys9uBMpk/xwZTYkUf6z+SWJTA0c8XG9ZPKbHr6Q+bK0gQXA9kQsSzvBzpZp0ZUtPtLEobdgJurmSOrmmJ3N98lEsKQTSNVCG+cDOAfK8ogTlsULkaxAFg9Pg3Cr/EXIMSKCBe7kRZuEUUPrzgst1A4gzcI8xN8HwhDT97FFMpt1KEVVb36GqjhWZ0g/9FQoWmlhrf/hx+BSumSJK07aZzw7YlsITllFRR3NaTtAaHFK658uCRT6m+eRepKZt0md10oLkqctxC5V/ENXYpw4hady3xXVe6jAQpX5WDQYFVUfAyM6JSMzBYMu87zITgPvLLkhkatd0TZkjt7/JMRMLfL7cb5NWp2wjDhir+dZPcWL+22YZeFdrR0kyxWMCkTE2kCt1W/fn0hBgXDg4XTwP+IudVEtQEwWjvQrA5C/bsR8noZ/imXySu8lDm9gSB1mBDeUViOl9n1HYUmNcgol0LeLe55BbAyousyIUgWzuwN0pQicWRDc98EjFq5fDpCZEasnTdIsfW6bOAoTg98b32H80km81uwzW+DZWAeo5Gz9fkrn1RsPt8/Az4i5ciuriREozfX95dl5SrpQuAwj7w/yZkojdzTWxlY6sPhfZyszVAqwD8144jN76KLM8R9lg/Wm0cFBVOasprT1CLgDnjFgjk=
  app: pipedrive-bling-integration
  on:
    repo: olucasgomes/pipedrive-bling-integration
